---
name: Terraform Validate

permissions:
  security-events: write
  actions: read
  contents: read

on:
  workflow_call:
    inputs:
      terraform_dir:
        description: 'Terraform directory to validate'
        required: false
        default: 'terraform'
        type: string
      tflint_config:
        description: 'Path to TFLint config file'
        required: false
        default: '.tflint.hcl'
        type: string
      terraform_version:
        description: 'Terraform version to use'
        required: false
        default: '1.13.3'
        type: string
      tflint_version:
        description: 'TFLint version to use'
        required: false
        default: 'v0.50.3'
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Checkout org-github-actions
        uses: actions/checkout@v5
        with:
          repository: govuk-one-login/org-github-actions
          ref: ${{ github.action_ref }}
          path: .github-actions

      - uses: ./.github-actions/terraform
        with:
          terraform_version: ${{ inputs.terraform_version }}
          terraform_dir: ${{ inputs.terraform_dir }}

      - uses: ./.github-actions/tflint
        with:
          tflint_version: ${{ inputs.tflint_version }}
          terraform_dir: ${{ inputs.terraform_dir }}
          tflint_config: ${{ inputs.tflint_config }}
